# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Modiles
      run: |
        go get -u go.riyazali.net/sqlite
        go get -u github.com/leekchan/accounting

    - name: Build
      run: go build -v -buildmode=c-shared -o s0.so ./...

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: osx-bin
        path: s0.so
        retention-days: 2
