name: Build Windows Version

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install Go Packages
      run: |
        go get -u go.riyazali.net/sqlite
        go get -u github.com/leekchan/accounting

    - name: Build
      run: go build -v -buildmode=c-shared -o s0-sqlite-extensions-win-amd64.dll ./...

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: osx-binary
        path: s0-sqlite-extensions-win-amd64.dll
        retention-days: 2
